export const INDIAN_STATES_AND_UTS = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi (NCT)',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
] as const;

export const NURSING_QUALIFICATIONS = [
  'ANM (Auxiliary Nursing & Midwifery)',
  'GNM (General Nursing & Midwifery)',
  'B.Sc. Nursing',
  'Post Basic B.Sc. Nursing',
  'M.Sc. Nursing',
  'M.Sc. Critical Care Nursing',
  'M.Sc. Pediatric Nursing',
  'M.Sc. Community Health Nursing',
  'M.Sc. Psychiatric Nursing',
  'Ph.D. Nursing',
  'Diploma in Critical Care Nursing',
  'Diploma in Emergency & Disaster Nursing',
  'Diploma in Neonatal Nursing',
  'Diploma in Operation Room Nursing',
  'Diploma in Oncology Nursing',
  'Nurse Practitioner in Critical Care (NPCC)',
  'Other / Equivalent Recognized Degree',
] as const;

export const HOSPITAL_TYPES = [
  'Multi-Specialty Hospital',
  'Super-Specialty Hospital',
  'Tertiary Care Hospital',
  'General / District Hospital',
  'Medical College & Research Institute',
  'Maternity & Child Care Hospital',
  'Critical Care & Trauma Center',
  'Trust / Charitable Hospital',
  'Private Nursing Home / Clinic',
  'Government Healthcare Institution',
  'Diagnostic & Daycare Center',
  'Other Healthcare Facility',
] as const;

export const HEALTHCARE_DEPARTMENTS = [
  'ICU / Intensive Care Unit',
  'Emergency / Trauma Care (ER)',
  'Operation Theatre (OT)',
  'Cardiology & CCU',
  'Pediatrics & PICU',
  'Neonatal ICU (NICU)',
  'Obstetrics & Gynecology (OBG)',
  'Oncology & Chemotherapy',
  'Neurology & Neurosurgery',
  'Nephrology & Dialysis Unit',
  'Orthopedics & Joint Replacement',
  'Gastroenterology',
  'Pulmonology & Respiratory Care',
  'General Medicine Ward',
  'General Surgery Ward',
  'Outpatient Department (OPD)',
  'Infection Control & Isolation',
  'Post-Anesthesia Care Unit (PACU)',
  'Home Healthcare / Palliative Care',
  'Other Specialized Department',
] as const;

export const NURSING_JOB_TITLES = [
  'Nursing Officer',
  'Staff Nurse',
  'Senior Staff Nurse',
  'ICU Staff Nurse',
  'Operation Theatre (OT) Nurse',
  'Emergency / Casualty Staff Nurse',
  'Pediatric / NICU Nurse',
  'Critical Care Nurse',
  'Dialysis Staff Nurse',
  'Cardiac Care Nurse',
  'Oncology Nurse',
  'Maternity / Labor Room Nurse',
  'Nurse In-Charge / Head Nurse',
  'Assistant Nursing Superintendent (ANS)',
  'Deputy Nursing Superintendent (DNS)',
  'Nursing Superintendent',
  'Clinical Nurse Specialist (CNS)',
  'Nurse Educator / Clinical Instructor',
  'Home Healthcare Nurse',
  'General Ward Nurse',
] as const;
