-- NURSECONNECT CONSOLIDATED DATABASE SCHEMA
-- Auto-generated by concatenating migrations 01 to 22 in exact chronological order
-- Target: Supabase PostgreSQL (SQL Editor -> New Query -> Run)

-- =============================================================================
-- [01/22] MIGRATION: 20260809164945_create_nurseconnect_schema.sql
-- =============================================================================

/*
# NurseConnect — Core Schema

## Overview
Creates the full database schema for NurseConnect, a platform connecting nurses
with hospitals for shift-based work.

## New Tables
1. profiles — user profiles with role (nurse/hospital/admin)
2. hospitals — hospital organization profiles
3. shifts — shift postings by hospitals
4. applications — nurse applications to shifts
5. reviews — post-shift reviews between nurses and hospitals

## Security (RLS)
All tables have RLS enabled with role-appropriate policies.
*/

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============ PROFILES ============
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('nurse', 'hospital', 'admin')),
  phone text,
  license_number text,
  specialty text,
  years_experience integer,
  bio text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_all" ON profiles;
CREATE POLICY "profiles_select_all" ON profiles FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "profiles_insert_own" ON profiles;
CREATE POLICY "profiles_insert_own" ON profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON profiles;
CREATE POLICY "profiles_update_own" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_delete_own" ON profiles;
CREATE POLICY "profiles_delete_own" ON profiles FOR DELETE
  TO authenticated USING (auth.uid() = id);

-- ============ HOSPITALS ============
CREATE TABLE IF NOT EXISTS hospitals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  location text NOT NULL,
  description text,
  website text,
  phone text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hospitals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hospitals_select_all" ON hospitals;
CREATE POLICY "hospitals_select_all" ON hospitals FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "hospitals_insert_own" ON hospitals;
CREATE POLICY "hospitals_insert_own" ON hospitals FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "hospitals_update_own" ON hospitals;
CREATE POLICY "hospitals_update_own" ON hospitals FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "hospitals_delete_own" ON hospitals;
CREATE POLICY "hospitals_delete_own" ON hospitals FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ SHIFTS ============
CREATE TABLE IF NOT EXISTS shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  department text NOT NULL,
  shift_type text NOT NULL CHECK (shift_type IN ('day', 'evening', 'night')),
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  hourly_rate numeric(10,2) NOT NULL,
  required_specialty text,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'filled', 'closed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shifts_select_all" ON shifts;
CREATE POLICY "shifts_select_all" ON shifts FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "shifts_insert_hospital_owner" ON shifts;
CREATE POLICY "shifts_insert_hospital_owner" ON shifts FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM hospitals WHERE hospitals.id = shifts.hospital_id AND hospitals.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "shifts_update_hospital_owner" ON shifts;
CREATE POLICY "shifts_update_hospital_owner" ON shifts FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM hospitals WHERE hospitals.id = shifts.hospital_id AND hospitals.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM hospitals WHERE hospitals.id = shifts.hospital_id AND hospitals.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "shifts_delete_hospital_owner" ON shifts;
CREATE POLICY "shifts_delete_hospital_owner" ON shifts FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM hospitals WHERE hospitals.id = shifts.hospital_id AND hospitals.user_id = auth.uid())
  );

-- ============ APPLICATIONS ============
CREATE TABLE IF NOT EXISTS applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id uuid NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  nurse_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'withdrawn')),
  cover_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (shift_id, nurse_id)
);

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "applications_select_nurse_or_hospital" ON applications;
CREATE POLICY "applications_select_nurse_or_hospital" ON applications FOR SELECT
  TO authenticated USING (
    nurse_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM shifts
      JOIN hospitals ON hospitals.id = shifts.hospital_id
      WHERE shifts.id = applications.shift_id AND hospitals.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "applications_insert_own" ON applications;
CREATE POLICY "applications_insert_own" ON applications FOR INSERT
  TO authenticated WITH CHECK (nurse_id = auth.uid());

DROP POLICY IF EXISTS "applications_update_hospital_status" ON applications;
CREATE POLICY "applications_update_hospital_status" ON applications FOR UPDATE
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM shifts
      JOIN hospitals ON hospitals.id = shifts.hospital_id
      WHERE shifts.id = applications.shift_id AND hospitals.user_id = auth.uid()
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM shifts
      JOIN hospitals ON hospitals.id = shifts.hospital_id
      WHERE shifts.id = applications.shift_id AND hospitals.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "applications_update_nurse_withdraw" ON applications;
CREATE POLICY "applications_update_nurse_withdraw" ON applications FOR UPDATE
  TO authenticated USING (nurse_id = auth.uid()) WITH CHECK (nurse_id = auth.uid());

DROP POLICY IF EXISTS "applications_delete_own" ON applications;
CREATE POLICY "applications_delete_own" ON applications FOR DELETE
  TO authenticated USING (nurse_id = auth.uid());

-- ============ REVIEWS ============
CREATE TABLE IF NOT EXISTS reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id uuid NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  reviewer_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewee_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewer_role text NOT NULL CHECK (reviewer_role IN ('nurse', 'hospital')),
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reviews_select_all" ON reviews;
CREATE POLICY "reviews_select_all" ON reviews FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "reviews_insert_own" ON reviews;
CREATE POLICY "reviews_insert_own" ON reviews FOR INSERT
  TO authenticated WITH CHECK (reviewer_id = auth.uid());

DROP POLICY IF EXISTS "reviews_update_own" ON reviews;
CREATE POLICY "reviews_update_own" ON reviews FOR UPDATE
  TO authenticated USING (reviewer_id = auth.uid()) WITH CHECK (reviewer_id = auth.uid());

DROP POLICY IF EXISTS "reviews_delete_own" ON reviews;
CREATE POLICY "reviews_delete_own" ON reviews FOR DELETE
  TO authenticated USING (reviewer_id = auth.uid());

-- ============ INDEXES ============
CREATE INDEX IF NOT EXISTS idx_shifts_hospital_id ON shifts(hospital_id);
CREATE INDEX IF NOT EXISTS idx_shifts_status ON shifts(status);
CREATE INDEX IF NOT EXISTS idx_shifts_start_time ON shifts(start_time);
CREATE INDEX IF NOT EXISTS idx_applications_shift_id ON applications(shift_id);
CREATE INDEX IF NOT EXISTS idx_applications_nurse_id ON applications(nurse_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewee_id ON reviews(reviewee_id);
CREATE INDEX IF NOT EXISTS idx_hospitals_user_id ON hospitals(user_id);

-- =============================================================================
-- [02/21] MIGRATION: 20260809170504_extend_profiles_and_hospitals.sql
-- =============================================================================

/*
# Extend profiles and hospitals tables for production NurseConnect

## Overview
Adds missing columns to the existing `profiles` and `hospitals` tables
to support the production recruitment platform. No data is lost — all
changes are additive ALTER TABLE statements using conditional DO blocks.

## Modified Tables

### profiles (existing — extended)
New columns added:
- `profile_photo` (text, nullable) — URL to profile photo
- `city` (text, nullable) — user's city
- `state` (text, nullable) — user's state
- `status` (text, not null, default 'active') — active / suspended / deactivated
- `verification_status` (text, not null, default 'pending') — pending / verified / rejected
- `updated_at` (timestamptz, default now()) — last modification timestamp

The existing columns (id, email, full_name, role, phone, license_number,
specialty, years_experience, bio, avatar_url, created_at) are preserved.
`avatar_url` remains for backward compatibility; `profile_photo` is the
canonical field going forward.

### hospitals (existing — extended)
New columns added:
- `hospital_name` (text, nullable) — canonical hospital name (existing `name` preserved)
- `hospital_type` (text, nullable) — government / private / trust / clinic
- `address` (text, nullable) — full street address
- `city` (text, nullable) — city
- `state` (text, nullable) — state
- `pincode` (text, nullable) — postal code
- `number_of_beds` (integer, nullable) — bed capacity
- `departments` (text, nullable) — comma-separated department list
- `contact_person` (text, nullable) — HR/contact person name
- `contact_email` (text, nullable) — contact email
- `verification_status` (text, not null, default 'pending') — pending / verified / rejected
- `updated_at` (timestamptz, default now()) — last modification timestamp

The existing columns (id, user_id, name, location, description, website,
phone, created_at) are preserved. `name` remains for backward compatibility;
`hospital_name` is the canonical field going forward.

## Security
- No policy changes in this migration — existing RLS policies remain intact.
- New columns inherit the existing table-level RLS.

## Notes
1. All ALTER TABLE additions use DO $$ ... IF NOT EXISTS ... END $$ blocks
   so the migration is safe to re-run.
2. `updated_at` columns have a trigger to auto-update on row modification.
3. No existing column is dropped, renamed, or type-changed.
*/

-- ============ PROFILES EXTENSION ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'profile_photo') THEN
    ALTER TABLE profiles ADD COLUMN profile_photo text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'city') THEN
    ALTER TABLE profiles ADD COLUMN city text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'state') THEN
    ALTER TABLE profiles ADD COLUMN state text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'status') THEN
    ALTER TABLE profiles ADD COLUMN status text NOT NULL DEFAULT 'active'
      CHECK (status IN ('active', 'suspended', 'deactivated'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'verification_status') THEN
    ALTER TABLE profiles ADD COLUMN verification_status text NOT NULL DEFAULT 'pending'
      CHECK (verification_status IN ('pending', 'verified', 'rejected'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'updated_at') THEN
    ALTER TABLE profiles ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
  END IF;
END $$;

-- ============ HOSPITALS EXTENSION ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'hospital_name') THEN
    ALTER TABLE hospitals ADD COLUMN hospital_name text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'hospital_type') THEN
    ALTER TABLE hospitals ADD COLUMN hospital_type text
      CHECK (hospital_type IN ('government', 'private', 'trust', 'clinic'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'address') THEN
    ALTER TABLE hospitals ADD COLUMN address text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'city') THEN
    ALTER TABLE hospitals ADD COLUMN city text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'state') THEN
    ALTER TABLE hospitals ADD COLUMN state text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'pincode') THEN
    ALTER TABLE hospitals ADD COLUMN pincode text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'number_of_beds') THEN
    ALTER TABLE hospitals ADD COLUMN number_of_beds integer;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'departments') THEN
    ALTER TABLE hospitals ADD COLUMN departments text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'contact_person') THEN
    ALTER TABLE hospitals ADD COLUMN contact_person text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'contact_email') THEN
    ALTER TABLE hospitals ADD COLUMN contact_email text;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'verification_status') THEN
    ALTER TABLE hospitals ADD COLUMN verification_status text NOT NULL DEFAULT 'pending'
      CHECK (verification_status IN ('pending', 'verified', 'rejected'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'hospitals' AND column_name = 'updated_at') THEN
    ALTER TABLE hospitals ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
  END IF;
END $$;

-- ============ AUTO-UPDATE TRIGGER FOR updated_at ============
-- Reusable function for auto-updating updated_at on row modification
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS profiles_updated_at ON profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS hospitals_updated_at ON hospitals;
CREATE TRIGGER hospitals_updated_at
  BEFORE UPDATE ON hospitals
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- [03/21] MIGRATION: 20260809170544_create_nurse_profiles.sql
-- =============================================================================

/*
# Create nurse_profiles table

## Overview
Creates a dedicated `nurse_profiles` table to store extended professional
information for nurses. Separate from `profiles` to keep the schema normalized.

## New Table: nurse_profiles
- `id` (uuid, PK)
- `nurse_id` (uuid, NOT NULL, FK → auth.users, UNIQUE, default auth.uid())
- `qualification` (text) — BSc Nursing, GNM, MSc Nursing, etc.
- `nursing_registration_number` (text) — official registration number
- `registration_authority` (text) — issuing authority
- `total_experience` (integer) — total years of experience
- `previous_hospital` (text) — last hospital worked at
- `departments` (text) — comma-separated departments/skills
- `preferred_location` (text) — preferred work location
- `expected_salary` (numeric(10,2)) — expected monthly salary
- `shift_preference` (text) — day / evening / night / flexible
- `accommodation_required` (boolean, default false)
- `availability` (text) — immediately / 2_weeks / 1_month / not_available
- `resume_url` (text) — URL to uploaded resume in private storage
- `verification_status` (text, default 'pending') — pending / verified / rejected
- `created_at` (timestamptz)
- `updated_at` (timestamptz, auto-updated)

## Security (RLS)
- SELECT: nurse reads own profile; admin reads all.
  Hospital read path (via applications) will be added in a later migration
  after the jobs table exists.
- INSERT/UPDATE/DELETE: nurse can only modify own row.

## Notes
1. nurse_id defaults to auth.uid() so insert works without passing it.
2. UNIQUE on nurse_id ensures one profile per nurse.
*/

CREATE TABLE IF NOT EXISTS nurse_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nurse_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  qualification text,
  nursing_registration_number text,
  registration_authority text,
  total_experience integer,
  previous_hospital text,
  departments text,
  preferred_location text,
  expected_salary numeric(10,2),
  shift_preference text CHECK (shift_preference IN ('day', 'evening', 'night', 'flexible')),
  accommodation_required boolean NOT NULL DEFAULT false,
  availability text CHECK (availability IN ('immediately', '2_weeks', '1_month', 'not_available')),
  resume_url text,
  verification_status text NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (nurse_id)
);

ALTER TABLE nurse_profiles ENABLE ROW LEVEL SECURITY;

-- SELECT: nurse reads own, admin reads all
DROP POLICY IF EXISTS "nurse_profiles_select_own_or_admin" ON nurse_profiles;
CREATE POLICY "nurse_profiles_select_own_or_admin"
ON nurse_profiles FOR SELECT
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- INSERT: nurse creates own
DROP POLICY IF EXISTS "nurse_profiles_insert_own" ON nurse_profiles;
CREATE POLICY "nurse_profiles_insert_own"
ON nurse_profiles FOR INSERT
TO authenticated WITH CHECK (nurse_id = auth.uid());

-- UPDATE: nurse updates own
DROP POLICY IF EXISTS "nurse_profiles_update_own" ON nurse_profiles;
CREATE POLICY "nurse_profiles_update_own"
ON nurse_profiles FOR UPDATE
TO authenticated USING (nurse_id = auth.uid()) WITH CHECK (nurse_id = auth.uid());

-- DELETE: nurse deletes own
DROP POLICY IF EXISTS "nurse_profiles_delete_own" ON nurse_profiles;
CREATE POLICY "nurse_profiles_delete_own"
ON nurse_profiles FOR DELETE
TO authenticated USING (nurse_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_nurse_profiles_nurse_id ON nurse_profiles(nurse_id);

DROP TRIGGER IF EXISTS nurse_profiles_updated_at ON nurse_profiles;
CREATE TRIGGER nurse_profiles_updated_at
  BEFORE UPDATE ON nurse_profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- [04/21] MIGRATION: 20260809170610_create_jobs.sql
-- =============================================================================

/*
# Create jobs table

## Overview
Creates the `jobs` table — the central entity for hospital job postings.
This is separate from the existing `shifts` table, which remains for
backward compatibility with the original shift-based model. The `jobs`
table supports a richer recruitment workflow with approval states,
salary ranges, vacancies, and skill matching.

## New Table: jobs
- `id` (uuid, PK)
- `hospital_id` (uuid, NOT NULL, FK → hospitals) — posting hospital
- `job_title` (text, NOT NULL)
- `department` (text, NOT NULL)
- `qualification_required` (text, nullable) — e.g. "BSc Nursing"
- `experience_required` (integer, nullable) — minimum years
- `salary_min` (numeric(10,2), nullable)
- `salary_max` (numeric(10,2), nullable)
- `location` (text, nullable) — job location
- `vacancies` (integer, default 1) — number of open positions
- `shift_id` (uuid, nullable, FK → shifts) — optional link to a shift
- `accommodation_available` (boolean, default false)
- `job_description` (text, nullable)
- `required_skills` (text, nullable) — comma-separated skills
- `status` (text, NOT NULL, default 'pending_approval')
  — draft / pending_approval / active / closed / rejected
- `created_at` (timestamptz)
- `updated_at` (timestamptz, auto-updated)

## Security (RLS)
- SELECT: all authenticated users can read jobs (nurses need to browse).
  Admins and the owning hospital can see all statuses; other users see
  only 'active' jobs. This is enforced via a USING predicate.
- INSERT: only the hospital owner can create jobs for their hospital.
- UPDATE: hospital owner can update their own jobs; admin can update any job.
- DELETE: hospital owner can delete their own jobs; admin can delete any.

## Notes
1. Jobs start as 'pending_approval' — admin must approve before they
   become 'active' and visible to nurses.
2. shift_id is optional — allows linking a job to a specific shift
   in the legacy shifts table if needed.
*/

CREATE TABLE IF NOT EXISTS jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  job_title text NOT NULL,
  department text NOT NULL,
  qualification_required text,
  experience_required integer,
  salary_min numeric(10,2),
  salary_max numeric(10,2),
  location text,
  vacancies integer NOT NULL DEFAULT 1,
  shift_id uuid REFERENCES shifts(id) ON DELETE SET NULL,
  accommodation_available boolean NOT NULL DEFAULT false,
  job_description text,
  required_skills text,
  status text NOT NULL DEFAULT 'pending_approval' CHECK (status IN ('draft', 'pending_approval', 'active', 'closed', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- SELECT: active jobs visible to all; all statuses visible to owner + admin
DROP POLICY IF EXISTS "jobs_select_visible" ON jobs;
CREATE POLICY "jobs_select_visible"
ON jobs FOR SELECT
TO authenticated USING (
  status = 'active'
  OR EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = jobs.hospital_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- INSERT: only hospital owner
DROP POLICY IF EXISTS "jobs_insert_hospital_owner" ON jobs;
CREATE POLICY "jobs_insert_hospital_owner"
ON jobs FOR INSERT
TO authenticated WITH CHECK (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = jobs.hospital_id AND hospitals.user_id = auth.uid()
  )
);

-- UPDATE: hospital owner or admin
DROP POLICY IF EXISTS "jobs_update_owner_or_admin" ON jobs;
CREATE POLICY "jobs_update_owner_or_admin"
ON jobs FOR UPDATE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = jobs.hospital_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = jobs.hospital_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- DELETE: hospital owner or admin
DROP POLICY IF EXISTS "jobs_delete_owner_or_admin" ON jobs;
CREATE POLICY "jobs_delete_owner_or_admin"
ON jobs FOR DELETE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = jobs.hospital_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

CREATE INDEX IF NOT EXISTS idx_jobs_hospital_id ON jobs(hospital_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_department ON jobs(department);
CREATE INDEX IF NOT EXISTS idx_jobs_location ON jobs(location);

DROP TRIGGER IF EXISTS jobs_updated_at ON jobs;
CREATE TRIGGER jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- [05/21] MIGRATION: 20260809170644_extend_applications_for_jobs.sql
-- =============================================================================

/*
# Extend applications table for job-based recruitment

## Overview
The existing `applications` table linked nurses to shifts. We now extend
it to also link nurses to jobs. The existing `shift_id` column is preserved
and a new `job_id` column is added. The `status` CHECK constraint is
expanded to include the new recruitment statuses. An `updated_at` column
and a unique constraint preventing duplicate job applications are added.

## Modified Table: applications (existing — extended)
New columns:
- `job_id` (uuid, nullable, FK → jobs) — the job being applied to
- `updated_at` (timestamptz, default now()) — last status change

Modified columns:
- `status` CHECK constraint expanded to include:
  applied / under_review / shortlisted / interview_scheduled / selected / joined / rejected
  The original statuses (pending / accepted / rejected / withdrawn) are kept
  for backward compatibility with existing shift applications.

New constraints:
- UNIQUE (job_id, nurse_id) — prevents duplicate applications to the same job

## Security (RLS) — policies updated
- SELECT: nurse sees own applications; hospital sees applications for
  their jobs (via jobs → hospitals) or their shifts (via shifts → hospitals);
  admin sees all.
- INSERT: nurse can insert own application.
- UPDATE: hospital owner (via job or shift) can update status; admin can
  update any; nurse can withdraw (update status to 'withdrawn' or 'rejected'
  on own row).
- DELETE: nurse can delete own; admin can delete any.

## Notes
1. job_id is nullable so legacy shift-based applications still work.
2. The status CHECK now allows both old and new status values.
3. UNIQUE (job_id, nurse_id) prevents the same nurse from applying to the
   same job twice. This does NOT affect shift-based applications.
4. All changes are additive — no data is lost.
*/

-- Add job_id column
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'applications' AND column_name = 'job_id') THEN
    ALTER TABLE applications ADD COLUMN job_id uuid REFERENCES jobs(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Add updated_at column
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'applications' AND column_name = 'updated_at') THEN
    ALTER TABLE applications ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
  END IF;
END $$;

-- Expand status CHECK constraint to include new recruitment statuses
-- Drop old constraint and add new one that allows both old and new values
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'applications_status_check'
      AND conrelid = 'applications'::regclass
  ) THEN
    ALTER TABLE applications DROP CONSTRAINT applications_status_check;
  END IF;
END $$;

ALTER TABLE applications ADD CONSTRAINT applications_status_check
  CHECK (status IN (
    'pending', 'accepted', 'rejected', 'withdrawn',
    'applied', 'under_review', 'shortlisted', 'interview_scheduled',
    'selected', 'joined'
  ));

-- Add unique constraint for job applications (prevents duplicate)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'applications_job_id_nurse_id_key'
      AND conrelid = 'applications'::regclass
  ) THEN
    ALTER TABLE applications ADD CONSTRAINT applications_job_id_nurse_id_key
      UNIQUE (job_id, nurse_id);
  END IF;
END $$;

-- updated_at trigger
DROP TRIGGER IF EXISTS applications_updated_at ON applications;
CREATE TRIGGER applications_updated_at
  BEFORE UPDATE ON applications
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_applications_job_id ON applications(job_id);

-- ============ REPLACE ALL POLICIES ============
-- Drop all old policies
DROP POLICY IF EXISTS "applications_select_nurse_or_hospital" ON applications;
DROP POLICY IF EXISTS "applications_insert_own" ON applications;
DROP POLICY IF EXISTS "applications_update_hospital_status" ON applications;
DROP POLICY IF EXISTS "applications_update_nurse_withdraw" ON applications;
DROP POLICY IF EXISTS "applications_delete_own" ON applications;

-- SELECT: nurse sees own; hospital sees apps for their jobs or shifts; admin sees all
CREATE POLICY "applications_select_nurse_hospital_admin"
ON applications FOR SELECT
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM jobs
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE jobs.id = applications.job_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM shifts
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE shifts.id = applications.shift_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- INSERT: nurse inserts own
CREATE POLICY "applications_insert_own"
ON applications FOR INSERT
TO authenticated WITH CHECK (nurse_id = auth.uid());

-- UPDATE: hospital owner (via job or shift) or admin or nurse (own)
CREATE POLICY "applications_update_hospital_or_admin_or_nurse"
ON applications FOR UPDATE
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM jobs
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE jobs.id = applications.job_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM shifts
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE shifts.id = applications.shift_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
) WITH CHECK (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM jobs
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE jobs.id = applications.job_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM shifts
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE shifts.id = applications.shift_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- DELETE: nurse deletes own; admin deletes any
CREATE POLICY "applications_delete_own_or_admin"
ON applications FOR DELETE
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- =============================================================================
-- [06/21] MIGRATION: 20260809170704_create_interviews.sql
-- =============================================================================

/*
# Create interviews table

## Overview
Creates the `interviews` table for scheduling interviews between hospitals
and nurse candidates. Each interview is linked to an application.

## New Table: interviews
- `id` (uuid, PK)
- `application_id` (uuid, NOT NULL, FK → applications ON DELETE CASCADE)
- `interview_date` (date, NOT NULL)
- `interview_time` (time, NOT NULL)
- `interview_type` (text, NOT NULL) — in_person / video / phone
- `meeting_link` (text, nullable) — for video interviews
- `location` (text, nullable) — for in-person interviews
- `notes` (text, nullable) — interview notes/instructions
- `status` (text, NOT NULL, default 'scheduled')
  — scheduled / completed / cancelled / rescheduled
- `created_at` (timestamptz)
- `updated_at` (timestamptz, auto-updated)

## Security (RLS)
- SELECT: nurse sees interviews for their own applications; hospital sees
  interviews for applications on their jobs; admin sees all.
- INSERT: hospital owner (via application → job → hospital) or admin.
- UPDATE: hospital owner or admin.
- DELETE: hospital owner or admin.

## Notes
1. Interview is linked to an application, which links to both a nurse
   and a job/hospital. Access is scoped through this chain.
2. Only hospitals schedule interviews — nurses cannot create them.
*/

CREATE TABLE IF NOT EXISTS interviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  interview_date date NOT NULL,
  interview_time time NOT NULL,
  interview_type text NOT NULL CHECK (interview_type IN ('in_person', 'video', 'phone')),
  meeting_link text,
  location text,
  notes text,
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled', 'rescheduled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE interviews ENABLE ROW LEVEL SECURITY;

-- Helper: can the current user manage this interview (hospital owner or admin)?
-- We inline this in each policy.

-- SELECT: nurse (via application.nurse_id), hospital (via application → job → hospital), admin
DROP POLICY IF EXISTS "interviews_select_nurse_hospital_admin" ON interviews;
CREATE POLICY "interviews_select_nurse_hospital_admin"
ON interviews FOR SELECT
TO authenticated USING (
  EXISTS (SELECT 1 FROM applications WHERE applications.id = interviews.application_id AND applications.nurse_id = auth.uid())
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN shifts ON shifts.id = applications.shift_id
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- INSERT: hospital owner or admin
DROP POLICY IF EXISTS "interviews_insert_hospital_or_admin" ON interviews;
CREATE POLICY "interviews_insert_hospital_or_admin"
ON interviews FOR INSERT
TO authenticated WITH CHECK (
  EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN shifts ON shifts.id = applications.shift_id
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- UPDATE: hospital owner or admin
DROP POLICY IF EXISTS "interviews_update_hospital_or_admin" ON interviews;
CREATE POLICY "interviews_update_hospital_or_admin"
ON interviews FOR UPDATE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN shifts ON shifts.id = applications.shift_id
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN shifts ON shifts.id = applications.shift_id
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- DELETE: hospital owner or admin
DROP POLICY IF EXISTS "interviews_delete_hospital_or_admin" ON interviews;
CREATE POLICY "interviews_delete_hospital_or_admin"
ON interviews FOR DELETE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN shifts ON shifts.id = applications.shift_id
    JOIN hospitals ON hospitals.id = shifts.hospital_id
    WHERE applications.id = interviews.application_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

CREATE INDEX IF NOT EXISTS idx_interviews_application_id ON interviews(application_id);
CREATE INDEX IF NOT EXISTS idx_interviews_status ON interviews(status);

DROP TRIGGER IF EXISTS interviews_updated_at ON interviews;
CREATE TRIGGER interviews_updated_at
  BEFORE UPDATE ON interviews
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- [07/21] MIGRATION: 20260809170731_create_document_tables.sql
-- =============================================================================

/*
# Create nurse_documents and hospital_documents tables

## Overview
Creates two document tables for secure storage of verification documents.
Documents are NOT publicly accessible — RLS ensures only the owner (and
admin for verification) can read them.

## New Table: nurse_documents
- `id` (uuid, PK)
- `nurse_id` (uuid, NOT NULL, FK → auth.users, default auth.uid())
- `document_type` (text, NOT NULL) — qualification / registration /
  experience / id_proof / resume / other
- `file_name` (text, NOT NULL) — original file name
- `file_url` (text, NOT NULL) — path in Supabase Storage (private bucket)
- `file_size` (bigint, nullable) — file size in bytes
- `mime_type` (text, nullable)
- `verification_status` (text, default 'pending') — pending / verified / rejected
- `created_at` (timestamptz)
- `updated_at` (timestamptz, auto-updated)

## New Table: hospital_documents
- `id` (uuid, PK)
- `hospital_id` (uuid, NOT NULL, FK → hospitals)
- `document_type` (text, NOT NULL) — registration / license / tax / other
- `file_name` (text, NOT NULL)
- `file_url` (text, NOT NULL) — path in Supabase Storage (private bucket)
- `file_size` (bigint, nullable)
- `mime_type` (text, nullable)
- `verification_status` (text, default 'pending')
- `created_at` (timestamptz)
- `updated_at` (timestamptz, auto-updated)

## Security (RLS)
### nurse_documents:
- SELECT: nurse reads own documents; admin reads all.
  Hospitals do NOT have direct read access — they see verified status
  through the application review flow.
- INSERT/UPDATE/DELETE: nurse manages own documents only.

### hospital_documents:
- SELECT: hospital owner reads own; admin reads all.
- INSERT/UPDATE/DELETE: hospital owner manages own only.

## Notes
1. file_url should reference a Supabase Storage path in a PRIVATE bucket.
   Access to the actual file content is controlled by Storage bucket
   policies, not just RLS. The frontend should use signed URLs for
   downloading.
2. These tables store metadata — the actual files live in Supabase Storage.
*/

-- ============ NURSE DOCUMENTS ============
CREATE TABLE IF NOT EXISTS nurse_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nurse_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  document_type text NOT NULL CHECK (document_type IN ('qualification', 'registration', 'experience', 'id_proof', 'resume', 'other')),
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  mime_type text,
  verification_status text NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE nurse_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "nurse_documents_select_own_or_admin" ON nurse_documents;
CREATE POLICY "nurse_documents_select_own_or_admin"
ON nurse_documents FOR SELECT
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "nurse_documents_insert_own" ON nurse_documents;
CREATE POLICY "nurse_documents_insert_own"
ON nurse_documents FOR INSERT
TO authenticated WITH CHECK (nurse_id = auth.uid());

DROP POLICY IF EXISTS "nurse_documents_update_own" ON nurse_documents;
CREATE POLICY "nurse_documents_update_own"
ON nurse_documents FOR UPDATE
TO authenticated USING (nurse_id = auth.uid()) WITH CHECK (nurse_id = auth.uid());

DROP POLICY IF EXISTS "nurse_documents_delete_own" ON nurse_documents;
CREATE POLICY "nurse_documents_delete_own"
ON nurse_documents FOR DELETE
TO authenticated USING (nurse_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_nurse_documents_nurse_id ON nurse_documents(nurse_id);

DROP TRIGGER IF EXISTS nurse_documents_updated_at ON nurse_documents;
CREATE TRIGGER nurse_documents_updated_at
  BEFORE UPDATE ON nurse_documents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============ HOSPITAL DOCUMENTS ============
CREATE TABLE IF NOT EXISTS hospital_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  document_type text NOT NULL CHECK (document_type IN ('registration', 'license', 'tax', 'other')),
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  mime_type text,
  verification_status text NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hospital_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hospital_documents_select_owner_or_admin" ON hospital_documents;
CREATE POLICY "hospital_documents_select_owner_or_admin"
ON hospital_documents FOR SELECT
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = hospital_documents.hospital_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "hospital_documents_insert_owner" ON hospital_documents;
CREATE POLICY "hospital_documents_insert_owner"
ON hospital_documents FOR INSERT
TO authenticated WITH CHECK (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = hospital_documents.hospital_id AND hospitals.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "hospital_documents_update_owner" ON hospital_documents;
CREATE POLICY "hospital_documents_update_owner"
ON hospital_documents FOR UPDATE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = hospital_documents.hospital_id AND hospitals.user_id = auth.uid()
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = hospital_documents.hospital_id AND hospitals.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "hospital_documents_delete_owner" ON hospital_documents;
CREATE POLICY "hospital_documents_delete_owner"
ON hospital_documents FOR DELETE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM hospitals
    WHERE hospitals.id = hospital_documents.hospital_id AND hospitals.user_id = auth.uid()
  )
);

CREATE INDEX IF NOT EXISTS idx_hospital_documents_hospital_id ON hospital_documents(hospital_id);

DROP TRIGGER IF EXISTS hospital_documents_updated_at ON hospital_documents;
CREATE TRIGGER hospital_documents_updated_at
  BEFORE UPDATE ON hospital_documents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- [08/21] MIGRATION: 20260809170757_create_notifications_and_saved_jobs.sql
-- =============================================================================

/*
# Create notifications and saved_jobs tables

## Overview
Creates two tables:
1. `notifications` — per-user notification feed
2. `saved_jobs` — nurses' bookmarked jobs

## New Table: notifications
- `id` (uuid, PK)
- `user_id` (uuid, NOT NULL, FK → auth.users, default auth.uid())
- `title` (text, NOT NULL)
- `message` (text, NOT NULL)
- `type` (text, NOT NULL) — application / interview / verification / job / system
- `is_read` (boolean, default false)
- `created_at` (timestamptz)

## New Table: saved_jobs
- `id` (uuid, PK)
- `nurse_id` (uuid, NOT NULL, FK → auth.users, default auth.uid())
- `job_id` (uuid, NOT NULL, FK → jobs)
- `created_at` (timestamptz)
- UNIQUE (nurse_id, job_id) — prevents duplicate saves

## Security (RLS)
### notifications:
- SELECT/UPDATE: user reads/marks-read only own notifications.
- INSERT: user or system can insert for the user themselves.
- DELETE: user deletes own.

### saved_jobs:
- SELECT: nurse sees own saved jobs.
- INSERT: nurse saves own.
- DELETE: nurse removes own.

## Notes
1. notifications.user_id defaults to auth.uid() for self-insertion.
2. saved_jobs has UNIQUE (nurse_id, job_id) to prevent duplicate saves.
*/

-- ============ NOTIFICATIONS ============
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL CHECK (type IN ('application', 'interview', 'verification', 'job', 'system')),
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select_own" ON notifications;
CREATE POLICY "notifications_select_own"
ON notifications FOR SELECT
TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "notifications_insert_own" ON notifications;
CREATE POLICY "notifications_insert_own"
ON notifications FOR INSERT
TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "notifications_update_own" ON notifications;
CREATE POLICY "notifications_update_own"
ON notifications FOR UPDATE
TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "notifications_delete_own" ON notifications;
CREATE POLICY "notifications_delete_own"
ON notifications FOR DELETE
TO authenticated USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);

-- ============ SAVED JOBS ============
CREATE TABLE IF NOT EXISTS saved_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nurse_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (nurse_id, job_id)
);

ALTER TABLE saved_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "saved_jobs_select_own" ON saved_jobs;
CREATE POLICY "saved_jobs_select_own"
ON saved_jobs FOR SELECT
TO authenticated USING (nurse_id = auth.uid());

DROP POLICY IF EXISTS "saved_jobs_insert_own" ON saved_jobs;
CREATE POLICY "saved_jobs_insert_own"
ON saved_jobs FOR INSERT
TO authenticated WITH CHECK (nurse_id = auth.uid());

DROP POLICY IF EXISTS "saved_jobs_delete_own" ON saved_jobs;
CREATE POLICY "saved_jobs_delete_own"
ON saved_jobs FOR DELETE
TO authenticated USING (nurse_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_saved_jobs_nurse_id ON saved_jobs(nurse_id);
CREATE INDEX IF NOT EXISTS idx_saved_jobs_job_id ON saved_jobs(job_id);

-- =============================================================================
-- [09/21] MIGRATION: 20260809170829_create_job_matches_and_matching.sql
-- =============================================================================

/*
# Create job_matches table and rule-based matching function

## Overview
Creates a `job_matches` table that stores pre-computed match scores between
nurses and jobs. A PL/pgSQL function `calculate_job_match` computes a
rule-based score using the specified weighted factors.

## New Table: job_matches
- `id` (uuid, PK)
- `job_id` (uuid, NOT NULL, FK → jobs)
- `nurse_id` (uuid, NOT NULL, FK → auth.users)
- `match_score` (numeric(5,2), NOT NULL, 0-100)
- `qualification_score` (numeric(5,2)) — 0-30
- `experience_score` (numeric(5,2)) — 0-25
- `skills_score` (numeric(5,2)) — 0-20
- `location_score` (numeric(5,2)) — 0-15
- `salary_score` (numeric(5,2)) — 0-10
- `created_at` (timestamptz)
- UNIQUE (job_id, nurse_id)

## New Function: calculate_job_match(p_job_id uuid, p_nurse_id uuid)
Returns a single row with the breakdown and total score.

### Matching factors and weights:
1. Qualification match (30%): compares job.qualification_required with
   nurse_profile.qualification. Exact match = 30, partial = 15, no match = 0.
2. Experience match (25%): compares job.experience_required with
   nurse_profile.total_experience. Meets/exceeds = 25, within 1 year = 15,
   else scaled.
3. Department/skills match (20%): compares job.required_skills with
   nurse_profile.departments. Overlap ratio determines score.
4. Location match (15%): compares job.location with
   nurse_profile.preferred_location. Exact = 15, same state = 8, else 0.
5. Salary match (10%): compares job.salary_max with
   nurse_profile.expected_salary. If salary_max >= expected = 10,
   if within 20% = 5, else 0.

## Security (RLS)
- SELECT: nurse sees matches for themselves; hospital sees matches for
  their jobs; admin sees all.
- INSERT/UPDATE/DELETE: admin only (matches are system-computed).

## Notes
1. The function is a SECURITY DEFINER function so it can read all
   relevant tables regardless of the caller's RLS. It is read-only
   (no writes) and returns only the score — no sensitive data.
2. The function is callable by authenticated users.
3. job_matches rows are typically populated by a batch job or on-demand
   by calling the function and inserting results.
*/

CREATE TABLE IF NOT EXISTS job_matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  nurse_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  match_score numeric(5,2) NOT NULL DEFAULT 0 CHECK (match_score >= 0 AND match_score <= 100),
  qualification_score numeric(5,2) NOT NULL DEFAULT 0,
  experience_score numeric(5,2) NOT NULL DEFAULT 0,
  skills_score numeric(5,2) NOT NULL DEFAULT 0,
  location_score numeric(5,2) NOT NULL DEFAULT 0,
  salary_score numeric(5,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, nurse_id)
);

ALTER TABLE job_matches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "job_matches_select_nurse_hospital_admin" ON job_matches;
CREATE POLICY "job_matches_select_nurse_hospital_admin"
ON job_matches FOR SELECT
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM jobs
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE jobs.id = job_matches.job_id AND hospitals.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "job_matches_insert_admin" ON job_matches;
CREATE POLICY "job_matches_insert_admin"
ON job_matches FOR INSERT
TO authenticated WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "job_matches_update_admin" ON job_matches;
CREATE POLICY "job_matches_update_admin"
ON job_matches FOR UPDATE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

DROP POLICY IF EXISTS "job_matches_delete_admin" ON job_matches;
CREATE POLICY "job_matches_delete_admin"
ON job_matches FOR DELETE
TO authenticated USING (
  EXISTS (
    SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

CREATE INDEX IF NOT EXISTS idx_job_matches_job_id ON job_matches(job_id);
CREATE INDEX IF NOT EXISTS idx_job_matches_nurse_id ON job_matches(nurse_id);
CREATE INDEX IF NOT EXISTS idx_job_matches_score ON job_matches(match_score DESC);

-- ============ MATCHING FUNCTION ============
-- Security definer so it can read all tables; read-only, returns only scores.
CREATE OR REPLACE FUNCTION calculate_job_match(p_job_id uuid, p_nurse_id uuid)
RETURNS TABLE (
  match_score numeric(5,2),
  qualification_score numeric(5,2),
  experience_score numeric(5,2),
  skills_score numeric(5,2),
  location_score numeric(5,2),
  salary_score numeric(5,2)
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job RECORD;
  v_nurse RECORD;
  v_qual_score numeric(5,2) := 0;
  v_exp_score numeric(5,2) := 0;
  v_skills_score numeric(5,2) := 0;
  v_loc_score numeric(5,2) := 0;
  v_salary_score numeric(5,2) := 0;
  v_job_skills text[];
  v_nurse_skills text[];
  v_overlap int := 0;
  v_total_skills int := 0;
  v_i int;
BEGIN
  -- Fetch job
  SELECT * INTO v_job FROM jobs WHERE id = p_job_id;
  IF NOT FOUND THEN
    RETURN QUERY SELECT 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2);
    RETURN;
  END IF;

  -- Fetch nurse profile
  SELECT * INTO v_nurse FROM nurse_profiles WHERE nurse_id = p_nurse_id;
  IF NOT FOUND THEN
    RETURN QUERY SELECT 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2), 0::numeric(5,2);
    RETURN;
  END IF;

  -- 1. Qualification (30%)
  IF v_job.qualification_required IS NOT NULL AND v_nurse.qualification IS NOT NULL THEN
    IF LOWER(TRIM(v_nurse.qualification)) = LOWER(TRIM(v_job.qualification_required)) THEN
      v_qual_score := 30;
    ELSIF POSITION(LOWER(TRIM(v_job.qualification_required)) IN LOWER(TRIM(v_nurse.qualification))) > 0
       OR POSITION(LOWER(TRIM(v_nurse.qualification)) IN LOWER(TRIM(v_job.qualification_required))) > 0 THEN
      v_qual_score := 15;
    END IF;
  END IF;

  -- 2. Experience (25%)
  IF v_job.experience_required IS NOT NULL AND v_nurse.total_experience IS NOT NULL THEN
    IF v_nurse.total_experience >= v_job.experience_required THEN
      v_exp_score := 25;
    ELSIF v_nurse.total_experience >= v_job.experience_required - 1 THEN
      v_exp_score := 15;
    ELSE
      v_exp_score := GREATEST(0, (v_nurse.total_experience::numeric / v_job.experience_required::numeric) * 25);
    END IF;
  END IF;

  -- 3. Skills/Departments (20%)
  IF v_job.required_skills IS NOT NULL AND v_nurse.departments IS NOT NULL THEN
    v_job_skills := string_to_array(LOWER(v_job.required_skills), ',');
    v_nurse_skills := string_to_array(LOWER(v_nurse.departments), ',');
    v_total_skills := array_length(v_job_skills, 1);
    IF v_total_skills > 0 THEN
      FOREACH v_i IN ARRAY v_job_skills LOOP
        IF TRIM(v_i) = ANY(v_nurse_skills) THEN
          v_overlap := v_overlap + 1;
        END IF;
      END LOOP;
      v_skills_score := (v_overlap::numeric / v_total_skills::numeric) * 20;
    END IF;
  END IF;

  -- 4. Location (15%)
  IF v_job.location IS NOT NULL AND v_nurse.preferred_location IS NOT NULL THEN
    IF LOWER(TRIM(v_nurse.preferred_location)) = LOWER(TRIM(v_job.location)) THEN
      v_loc_score := 15;
    ELSIF POSITION(LOWER(TRIM(v_job.location)) IN LOWER(TRIM(v_nurse.preferred_location))) > 0 THEN
      v_loc_score := 8;
    END IF;
  END IF;

  -- 5. Salary (10%)
  IF v_job.salary_max IS NOT NULL AND v_nurse.expected_salary IS NOT NULL THEN
    IF v_job.salary_max >= v_nurse.expected_salary THEN
      v_salary_score := 10;
    ELSIF v_job.salary_max >= v_nurse.expected_salary * 0.8 THEN
      v_salary_score := 5;
    END IF;
  END IF;

  RETURN QUERY SELECT
    (v_qual_score + v_exp_score + v_skills_score + v_loc_score + v_salary_score)::numeric(5,2),
    v_qual_score,
    v_exp_score,
    v_skills_score,
    v_loc_score,
    v_salary_score;
  RETURN;
END;
$$;

-- Grant execute to authenticated
GRANT EXECUTE ON FUNCTION calculate_job_match(uuid, uuid) TO authenticated;

-- =============================================================================
-- [10/21] MIGRATION: 20260809170853_update_reviews_and_admin_helper.sql
-- =============================================================================

/*
# Update nurse_profiles, reviews policies, and add is_admin helper

## Overview
Three changes:
1. Replace nurse_profiles SELECT policy to add hospital read path
   (hospitals can read nurse_profiles for nurses who applied to their jobs).
2. Replace reviews INSERT policy to enforce that reviews can only be
   left after a completed/selected/joined recruitment relationship.
3. Create an `is_admin()` SQL helper function for cleaner policy predicates.

## Modified Table: nurse_profiles
- SELECT policy replaced: now allows hospitals to read nurse_profiles
  for nurses who have applied to their jobs (via applications → jobs → hospitals).
  Also retains nurse-self-read and admin-read.

## Modified Table: reviews
- INSERT policy replaced: a review can only be inserted if there exists
  an application between the reviewer and reviewee that reached
  'selected' or 'joined' status, OR a shift application with 'accepted' status.
- SELECT/UPDATE/DELETE policies remain unchanged.

## New Function: is_admin()
- SECURITY DEFINER function that checks if the current auth.uid() has
  role='admin' in profiles.
- Used to simplify RLS policies across tables.

## Notes
1. is_admin() is SECURITY DEFINER to avoid recursive RLS on profiles
   when querying role. It only reads the role column — no sensitive data.
2. The reviews INSERT check covers both job-based and shift-based
   applications (backward compatible).
*/

-- ============ is_admin() HELPER ============
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  );
$$;

GRANT EXECUTE ON FUNCTION is_admin() TO authenticated;

-- ============ UPDATE nurse_profiles SELECT POLICY ============
DROP POLICY IF EXISTS "nurse_profiles_select_own_or_admin" ON nurse_profiles;
DROP POLICY IF EXISTS "nurse_profiles_select_own_or_hospital_or_admin" ON nurse_profiles;

CREATE POLICY "nurse_profiles_select_own_or_hospital_or_admin"
ON nurse_profiles FOR SELECT
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.nurse_id = nurse_profiles.nurse_id
      AND hospitals.user_id = auth.uid()
  )
  OR is_admin()
);

-- ============ UPDATE reviews INSERT POLICY ============
-- Reviews can only be left after a completed recruitment relationship:
-- - For job applications: status must be 'selected' or 'joined'
-- - For shift applications: status must be 'accepted'
DROP POLICY IF EXISTS "reviews_insert_own" ON reviews;

CREATE POLICY "reviews_insert_own"
ON reviews FOR INSERT
TO authenticated WITH CHECK (
  reviewer_id = auth.uid()
  AND (
    -- Job-based: reviewer and reviewee connected via a selected/joined application
    EXISTS (
      SELECT 1 FROM applications
      WHERE applications.status IN ('selected', 'joined')
        AND (
          (applications.nurse_id = reviewer_id AND applications.nurse_id = reviewee_id)
          OR EXISTS (
            SELECT 1 FROM jobs
            JOIN hospitals ON hospitals.id = jobs.hospital_id
            WHERE jobs.id = applications.job_id
              AND hospitals.user_id = reviewee_id
              AND applications.nurse_id = reviewer_id
          )
          OR EXISTS (
            SELECT 1 FROM jobs
            JOIN hospitals ON hospitals.id = jobs.hospital_id
            WHERE jobs.id = applications.job_id
              AND hospitals.user_id = reviewer_id
              AND applications.nurse_id = reviewee_id
          )
        )
    )
    OR
    -- Shift-based (legacy): reviewer and reviewee connected via an accepted application
    EXISTS (
      SELECT 1 FROM applications
      WHERE applications.status = 'accepted'
        AND (
          (applications.nurse_id = reviewer_id)
          OR EXISTS (
            SELECT 1 FROM shifts
            JOIN hospitals ON hospitals.id = shifts.hospital_id
            WHERE shifts.id = applications.shift_id
              AND hospitals.user_id = reviewer_id
          )
        )
        AND (
          applications.nurse_id = reviewee_id
          OR EXISTS (
            SELECT 1 FROM shifts
            JOIN hospitals ON hospitals.id = shifts.hospital_id
            WHERE shifts.id = applications.shift_id
              AND hospitals.user_id = reviewee_id
          )
        )
    )
  )
);

-- Also update reviews SELECT to use is_admin for consistency
-- (keeps existing behavior: all authenticated can read reviews)
-- No change needed — reviews_select_all already allows all authenticated.

-- Update reviews UPDATE and DELETE to also allow admin
DROP POLICY IF EXISTS "reviews_update_own" ON reviews;
CREATE POLICY "reviews_update_own"
ON reviews FOR UPDATE
TO authenticated USING (reviewer_id = auth.uid() OR is_admin())
WITH CHECK (reviewer_id = auth.uid() OR is_admin());

DROP POLICY IF EXISTS "reviews_delete_own" ON reviews;
CREATE POLICY "reviews_delete_own"
ON reviews FOR DELETE
TO authenticated USING (reviewer_id = auth.uid() OR is_admin());

-- =============================================================================
-- [11/21] MIGRATION: 20260809170915_fix_security_advisor_warnings.sql
-- =============================================================================

/*
# Fix security advisor warnings

## Overview
Fixes 5 security advisor warnings:
1. Revoke EXECUTE on is_admin() and calculate_job_match() from anon role
   so unauthenticated users cannot call these SECURITY DEFINER functions.
2. Set explicit search_path on update_updated_at_column() to fix the
   mutable search_path warning.

## Security Changes
- REVOKE EXECUTE ON FUNCTION is_admin() FROM anon
- REVOKE EXECUTE ON FUNCTION calculate_job_match(uuid, uuid) FROM anon
- ALTER FUNCTION update_updated_at_column() SET search_path = public

## Notes
1. is_admin() and calculate_job_match() are still executable by authenticated.
2. These are intentional SECURITY DEFINER functions — they need to read
   tables that the caller might not have direct SELECT access to. Restricting
   to authenticated ensures only signed-in users can invoke them.
*/

REVOKE EXECUTE ON FUNCTION is_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION calculate_job_match(uuid, uuid) FROM anon;

ALTER FUNCTION update_updated_at_column() SET search_path = public;

-- =============================================================================
-- [12/21] MIGRATION: 20260809170933_fix_function_grants_public.sql
-- =============================================================================

/*
# Fix SECURITY DEFINER function execute grants

## Overview
The previous revocation from `anon` was insufficient because PostgreSQL
grants EXECUTE to `PUBLIC` by default (which includes all roles).
This migration revokes EXECUTE from PUBLIC and grants it only to
`authenticated`, so only signed-in users can call these functions.

## Security Changes
- REVOKE EXECUTE ON all SECURITY DEFINER functions FROM PUBLIC
- GRANT EXECUTE only TO authenticated
*/

REVOKE EXECUTE ON FUNCTION is_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION calculate_job_match(uuid, uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION calculate_job_match(uuid, uuid) TO authenticated;

-- =============================================================================
-- [13/21] MIGRATION: 20260810050638_make_shift_id_nullable_for_job_applications.sql
-- =============================================================================

/*
# Fix: allow job-based applications without shift_id

The original `applications` table had `shift_id` as NOT NULL because
legacy applications were shift-based. V2 applications are job-based and
do not provide a shift_id, causing a NOT NULL violation on insert.

This migration makes shift_id nullable so:
  - V2 job applications can be created with job_id only (shift_id = NULL)
  - Legacy shift-based applications are preserved and still work
  - No data is deleted or altered
  - Existing UNIQUE(job_id, nurse_id) constraint is preserved
*/

ALTER TABLE applications ALTER COLUMN shift_id DROP NOT NULL;

-- =============================================================================
-- [14/21] MIGRATION: 20260810052849_fix_application_nurse_fk_and_nurse_profiles_rls.sql
-- =============================================================================

/*
# Fix application read flow — missing FKs and nurse_profiles RLS

## Problem
The V2 frontend queries applications with embedded relations:
  applications?select=*,jobs(*,hospitals(...)),profiles(...),nurse_profiles(...),interviews(*)

PostgREST resolves embedded relations using FOREIGN KEY constraints.
The `applications.nurse_id` column had a FK to `auth.users(id)` but NO FK
to `profiles(id)`. Same for `nurse_profiles.nurse_id`. Without these FKs,
PostgREST cannot resolve the `profiles(...)` or `nurse_profiles(...)`
embeds, so the ENTIRE query returns an error / zero rows. This is why
applications were invisible to nurses, hospitals, and admins despite
existing in the database.

Additionally, the `nurse_profiles` SELECT policy only allowed the nurse
themselves or an admin to read rows. Hospitals need to read nurse_profiles
for applicants to their jobs, but were blocked by RLS — so even if the
embed resolved, the nurse_profiles data would be null.

## Fix 1: Add FK from applications.nurse_id → profiles.id
This lets PostgREST resolve `applications?select=...,profiles(...)`.
The existing FK to auth.users(id) is preserved.

## Fix 2: Add FK from nurse_profiles.nurse_id → profiles.id
This lets PostgREST resolve `applications?select=...,nurse_profiles(...)`.
The existing FK to auth.users(id) is preserved.

## Fix 3: Update nurse_profiles SELECT policy
Allow hospitals to read nurse_profiles when the nurse has applied to a
job owned by that hospital. This is scoped via:
  EXISTS (SELECT 1 FROM applications
          JOIN jobs ON jobs.id = applications.job_id
          JOIN hospitals ON hospitals.id = jobs.hospital_id
          WHERE applications.nurse_id = nurse_profiles.nurse_id
            AND hospitals.user_id = auth.uid())

## Data Safety
- No tables created or deleted.
- No columns added, removed, or renamed.
- No data modified.
- All existing FKs and constraints preserved.
- RLS remains enabled on all tables.
*/

-- ============ FIX 1: applications.nurse_id → profiles.id ============
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'applications_nurse_id_profiles_fkey'
      AND conrelid = 'applications'::regclass
  ) THEN
    ALTER TABLE applications
      ADD CONSTRAINT applications_nurse_id_profiles_fkey
      FOREIGN KEY (nurse_id) REFERENCES profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

-- ============ FIX 2: nurse_profiles.nurse_id → profiles.id ============
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'nurse_profiles_nurse_id_profiles_fkey'
      AND conrelid = 'nurse_profiles'::regclass
  ) THEN
    ALTER TABLE nurse_profiles
      ADD CONSTRAINT nurse_profiles_nurse_id_profiles_fkey
      FOREIGN KEY (nurse_id) REFERENCES profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

-- ============ FIX 3: nurse_profiles SELECT policy ============
-- Drop old policy and recreate with hospital read path
DROP POLICY IF EXISTS "nurse_profiles_select_own_or_admin" ON nurse_profiles;
DROP POLICY IF EXISTS "nurse_profiles_select_own_hospital_or_admin" ON nurse_profiles;

CREATE POLICY "nurse_profiles_select_own_hospital_or_admin"
ON nurse_profiles FOR SELECT
TO authenticated USING (
  nurse_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
  OR EXISTS (
    SELECT 1 FROM applications
    JOIN jobs ON jobs.id = applications.job_id
    JOIN hospitals ON hospitals.id = jobs.hospital_id
    WHERE applications.nurse_id = nurse_profiles.nurse_id
      AND hospitals.user_id = auth.uid()
  )
);

-- =============================================================================
-- [15/21] MIGRATION: 20260810052935_remove_duplicate_nurse_profiles_select_policy.sql
-- =============================================================================

/*
# Remove duplicate nurse_profiles SELECT policy

Two SELECT policies existed on nurse_profiles:
  1. nurse_profiles_select_own_hospital_or_admin (new — from previous fix)
  2. nurse_profiles_select_own_or_hospital_or_admin (old — from a prior migration)

Both are permissive and don't conflict, but having two is redundant.
Drop the old one to keep the policy set clean.
*/

DROP POLICY IF EXISTS "nurse_profiles_select_own_or_hospital_or_admin" ON nurse_profiles;

-- =============================================================================
-- [16/21] MIGRATION: 20260810055114_add_applications_nurse_profiles_fk.sql
-- =============================================================================

/*
# Fix HospitalPortal applications query — add FK applications → nurse_profiles

## Problem
The HospitalPortal ReviewApplications component queries:
  applications?select=*,profiles(...),nurse_profiles(...),interviews(*)

PostgREST resolves embedded relations using foreign keys. There was no FK
between `applications` and `nurse_profiles`, so PostgREST could not resolve
the `nurse_profiles(...)` embed. This caused the ENTIRE query to fail,
returning null/zero rows — the hospital saw no applications at all.

The NursePortal and AdminPortal queries do not embed nurse_profiles from
applications, so they were not affected by this specific issue (they were
fixed by the previous FK additions to profiles).

## Fix
Add a FK from `applications.nurse_id` → `nurse_profiles.nurse_id`.
Since `nurse_profiles.nurse_id` has a UNIQUE constraint, this is a valid
FK target. This lets PostgREST resolve `applications?select=...,nurse_profiles(...)`.

The existing FKs (applications.nurse_id → profiles.id, auth.users.id) are
preserved. RLS is not affected — the nurse_profiles SELECT policy already
allows hospitals to read nurse_profiles for applicants to their jobs.

## Data Safety
- No tables created or deleted.
- No columns added, removed, or renamed.
- No data modified.
- RLS unchanged.
*/

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'applications_nurse_id_nurse_profiles_fkey'
      AND conrelid = 'applications'::regclass
  ) THEN
    ALTER TABLE applications
      ADD CONSTRAINT applications_nurse_id_nurse_profiles_fkey
      FOREIGN KEY (nurse_id) REFERENCES nurse_profiles(nurse_id) ON DELETE CASCADE;
  END IF;
END $$;

-- Reload PostgREST schema cache so the new FK is picked up immediately
NOTIFY pgrst, 'reload schema';

-- =============================================================================
-- [17/21] MIGRATION: 20260810055448_add_admin_update_policies_for_verification.sql
-- =============================================================================

/*
# Add admin UPDATE policies for verification workflow

## Problem
The RLS UPDATE policies on `profiles`, `nurse_profiles`, and `hospitals`
only allow the row owner to update (`auth.uid() = id`). When an admin
clicks Verify/Reject in the Admin Portal, the update is silently blocked
by RLS because the admin's auth.uid() does not match the target profile's
id. The verification never takes effect.

## Fix
Add admin-scoped UPDATE policies on all three tables. These allow any
authenticated user whose profile role is 'admin' to update rows, alongside
the existing owner-only policies. Both policies are permissive (OR logic),
so the owner can still update their own row and the admin can update any
row for verification purposes.

## Data Safety
- No tables created or deleted.
- No columns added, removed, or renamed.
- No data modified.
- RLS remains enabled on all tables.
- Existing owner UPDATE policies are preserved.
*/

-- ============ profiles: admin can update ============
DROP POLICY IF EXISTS "profiles_update_admin" ON profiles;
CREATE POLICY "profiles_update_admin" ON profiles FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ nurse_profiles: admin can update ============
DROP POLICY IF EXISTS "nurse_profiles_update_admin" ON nurse_profiles;
CREATE POLICY "nurse_profiles_update_admin" ON nurse_profiles FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- ============ hospitals: admin can update ============
DROP POLICY IF EXISTS "hospitals_update_admin" ON hospitals;
CREATE POLICY "hospitals_update_admin" ON hospitals FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- =============================================================================
-- [18/21] MIGRATION: 20260811070136_enforce_interview_before_selection.sql
-- =============================================================================

/*
# Enforce interview-before-selection workflow at the database level

## Problem
A hospital can set an application status to 'selected' directly from
'shortlisted', bypassing the interview stage entirely. The UI should
prevent this, but we also need a database-level guard so the rule
cannot be bypassed by any client.

## Fix
Add a BEFORE UPDATE trigger on `applications` that rejects any update
to status = 'selected' unless a related interview exists with
status = 'completed'. This is the server-side enforcement that
complements the UI hiding of the Select button.

## Data Safety
- No tables created or deleted.
- No columns added, removed, or renamed.
- No data modified.
- RLS unchanged.
- Existing applications and interviews preserved.
*/

CREATE OR REPLACE FUNCTION public.enforce_interview_before_selection()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only enforce when transitioning TO 'selected'
  IF NEW.status = 'selected' AND OLD.status <> 'selected' THEN
    -- Must have at least one completed interview for this application
    IF NOT EXISTS (
      SELECT 1 FROM interviews
      WHERE interviews.application_id = NEW.id
        AND interviews.status = 'completed'
    ) THEN
      RAISE EXCEPTION 'Cannot select an applicant without a completed interview';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_enforce_interview_before_selection ON applications;
CREATE TRIGGER trigger_enforce_interview_before_selection
  BEFORE UPDATE ON applications
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_interview_before_selection();

-- Revoke execute from anon/authenticated so it can only be called by the trigger
REVOKE EXECUTE ON FUNCTION public.enforce_interview_before_selection() FROM anon, authenticated;

-- =============================================================================
-- [19/21] MIGRATION: 20260812085927_create_nurse_documents_storage_bucket_and_policies.sql
-- =============================================================================

/*
# Create nurse-documents storage bucket with secure RLS policies

1. Storage Changes
- Create a PRIVATE bucket named `nurse-documents` (public = false).
- No existing buckets are deleted.

2. Storage RLS Policies (on storage.objects)
- Nurses can upload files only to a path prefixed with their own auth.uid().
- Nurses can read/download only their own files (path = auth.uid()/...).
- Nurses can delete only their own files.
- Admins (profiles.role = 'admin') can read any file in the bucket for verification purposes.
- Hospital users get access only via signed URLs generated by the server/admin — NOT via storage RLS.
- Uses signed URLs for downloads so private files are never made public.

3. Security Notes
- Bucket is private: files are NOT publicly readable.
- Path-based isolation: each nurse's files live under `<uid>/` prefix, enforced by RLS.
- Admin read access is scoped to the admin role check via profiles table.
*/

-- Create the private bucket (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'nurse-documents',
  'nurse-documents',
  false,
  10485760,  -- 10 MB limit
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain']
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Storage RLS policies on storage.objects for nurse-documents
-- ============================================================

-- Nurses can upload to their own folder
DROP POLICY IF EXISTS "nurse_docs_upload_own" ON storage.objects;
CREATE POLICY "nurse_docs_upload_own"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'nurse-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Nurses can read their own files
DROP POLICY IF EXISTS "nurse_docs_read_own" ON storage.objects;
CREATE POLICY "nurse_docs_read_own"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Nurses can delete their own files
DROP POLICY IF EXISTS "nurse_docs_delete_own" ON storage.objects;
CREATE POLICY "nurse_docs_delete_own"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Admins can read any file in nurse-documents for verification
DROP POLICY IF EXISTS "nurse_docs_admin_read" ON storage.objects;
CREATE POLICY "nurse_docs_admin_read"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Admins can delete any file in nurse-documents (e.g. during moderation)
DROP POLICY IF EXISTS "nurse_docs_admin_delete" ON storage.objects;
CREATE POLICY "nurse_docs_admin_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- =============================================================================
-- [20/21] MIGRATION: 20260812085935_add_saved_jobs_unique_constraint.sql
-- =============================================================================

/*
# Prevent duplicate saved_jobs records

1. Database Changes
- Add a UNIQUE constraint on (nurse_id, job_id) in saved_jobs so a nurse
  cannot save the same job twice.
- Uses IF NOT EXISTS pattern to be idempotent.

2. Security Notes
- No RLS changes. Existing saved_jobs policies remain intact.
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'saved_jobs_nurse_job_unique'
  ) THEN
    ALTER TABLE saved_jobs ADD CONSTRAINT saved_jobs_nurse_job_unique UNIQUE (nurse_id, job_id);
  END IF;
END $$;

-- =============================================================================
-- [21/21] MIGRATION: 20260812090038_create_hospital_docs_bucket_and_notification_function.sql
-- =============================================================================

/*
# 1. Create hospital-documents storage bucket with secure RLS policies
# 2. Create create_notification SECURITY DEFINER function for cross-user notifications
*/

-- ============================================================
-- 1. hospital-documents PRIVATE bucket
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'hospital-documents',
  'hospital-documents',
  false,
  10485760,
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain']
)
ON CONFLICT (id) DO NOTHING;

-- Hospital owner can upload to their folder (path = hospital_id/...)
DROP POLICY IF EXISTS "hospital_docs_upload_own" ON storage.objects;
CREATE POLICY "hospital_docs_upload_own"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'hospital-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Hospital owner can read their own files
DROP POLICY IF EXISTS "hospital_docs_read_own" ON storage.objects;
CREATE POLICY "hospital_docs_read_own"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'hospital-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Hospital owner can delete their own files
DROP POLICY IF EXISTS "hospital_docs_delete_own" ON storage.objects;
CREATE POLICY "hospital_docs_delete_own"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'hospital-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Admins can read any hospital document
DROP POLICY IF EXISTS "hospital_docs_admin_read" ON storage.objects;
CREATE POLICY "hospital_docs_admin_read"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'hospital-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Admins can delete any hospital document
DROP POLICY IF EXISTS "hospital_docs_admin_delete" ON storage.objects;
CREATE POLICY "hospital_docs_admin_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'hospital-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- ============================================================
-- 2. create_notification SECURITY DEFINER function
-- Allows any authenticated user to create a notification for any user.
-- This is needed because notifications RLS requires user_id = auth.uid()
-- for inserts, but hospitals need to notify nurses and vice versa.
-- ============================================================

CREATE OR REPLACE FUNCTION public.create_notification(
  p_user_id uuid,
  p_title text,
  p_message text,
  p_type text DEFAULT 'system'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO notifications (user_id, title, message, type)
  VALUES (p_user_id, p_title, p_message, p_type);
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_notification TO authenticated;

-- =============================================================================
-- [22/22] MIGRATION: 20260823061000_prevent_privilege_escalation.sql
-- =============================================================================

/*
# Prevent privilege escalation and unauthorized verification status modifications

## Vulnerability Addressed
Authenticated users (nurses or hospitals) could previously execute direct UPDATE queries
against `public.profiles` changing `role = 'admin'` or `verification_status = 'verified'`
due to unrestricted column updates in the owner update RLS policy.

## Fix
1. Create `protect_profile_sensitive_fields()` BEFORE UPDATE / INSERT trigger function:
   - Validates that non-admin users cannot alter `role` or `verification_status`.
   - Rejects unauthorized changes with error 42501 (insufficient_privilege).
   - Allows platform administrators (verified via `is_admin()`) to update any role or verification status.
   - Allows backend/service role processes (where `auth.uid() IS NULL`) to operate unimpeded.
   - Allows users to update all other self-editable profile fields (full_name, phone, bio, city, state, etc.).
2. Create `protect_nurse_profile_verification_status()` BEFORE UPDATE trigger function for `nurse_profiles`.
3. Create `protect_hospital_verification_status()` BEFORE UPDATE trigger function for `hospitals`.
4. Attach BEFORE UPDATE triggers to `profiles`, `nurse_profiles`, and `hospitals`.

## Data Safety
- No tables created or deleted.
- No columns added, removed, or renamed.
- No legitimate data modified.
- Existing RLS policies remain intact.
*/

-- ============ FUNCTION: protect_profile_sensitive_fields ============
CREATE OR REPLACE FUNCTION public.protect_profile_sensitive_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Allow service-role / background migrations where auth.uid() is null
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  -- If user is NOT an administrator, enforce column-level immutability
  IF NOT public.is_admin() THEN
    -- Check role mutation
    IF TG_OP = 'UPDATE' AND NEW.role IS DISTINCT FROM OLD.role THEN
      RAISE EXCEPTION 'Unauthorized: Only platform administrators can change user roles.'
        USING ERRCODE = '42501';
    END IF;

    -- Check verification_status mutation
    IF TG_OP = 'UPDATE' AND NEW.verification_status IS DISTINCT FROM OLD.verification_status THEN
      RAISE EXCEPTION 'Unauthorized: Only platform administrators can change verification status.'
        USING ERRCODE = '42501';
    END IF;

    -- Check direct insert escalation
    IF TG_OP = 'INSERT' THEN
      IF NEW.role = 'admin' THEN
        RAISE EXCEPTION 'Unauthorized: Cannot register directly as platform administrator.'
          USING ERRCODE = '42501';
      END IF;
      IF NEW.verification_status = 'verified' THEN
        RAISE EXCEPTION 'Unauthorized: Initial profile cannot be self-verified.'
          USING ERRCODE = '42501';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- ============ FUNCTION: protect_nurse_profile_verification_status ============
CREATE OR REPLACE FUNCTION public.protect_nurse_profile_verification_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT public.is_admin() THEN
    IF TG_OP = 'UPDATE' AND NEW.verification_status IS DISTINCT FROM OLD.verification_status THEN
      RAISE EXCEPTION 'Unauthorized: Only platform administrators can change verification status.'
        USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- ============ FUNCTION: protect_hospital_verification_status ============
CREATE OR REPLACE FUNCTION public.protect_hospital_verification_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT public.is_admin() THEN
    IF TG_OP = 'UPDATE' AND NEW.verification_status IS DISTINCT FROM OLD.verification_status THEN
      RAISE EXCEPTION 'Unauthorized: Only platform administrators can change verification status.'
        USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- ============ ATTACH TRIGGERS ============
DROP TRIGGER IF EXISTS trg_protect_profile_sensitive_fields ON public.profiles;
CREATE TRIGGER trg_protect_profile_sensitive_fields
  BEFORE INSERT OR UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_profile_sensitive_fields();

DROP TRIGGER IF EXISTS trg_protect_nurse_profile_verification_status ON public.nurse_profiles;
CREATE TRIGGER trg_protect_nurse_profile_verification_status
  BEFORE UPDATE ON public.nurse_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_nurse_profile_verification_status();

DROP TRIGGER IF EXISTS trg_protect_hospital_verification_status ON public.hospitals;
CREATE TRIGGER trg_protect_hospital_verification_status
  BEFORE UPDATE ON public.hospitals
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_hospital_verification_status();

-- Revoke direct execution permissions so functions can only be invoked by triggers
REVOKE EXECUTE ON FUNCTION public.protect_profile_sensitive_fields() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_nurse_profile_verification_status() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_hospital_verification_status() FROM anon, authenticated;


-- =============================================================================
-- [23/23] MIGRATION: 20260824080000_clean_test_data_and_admin_delete_policies.sql
-- =============================================================================

/*
# Clean Test Data & Add Admin DELETE Policies
*/

-- ============ 1. ADMIN DELETE POLICIES ============

-- profiles: admin can delete test profiles
DROP POLICY IF EXISTS "profiles_delete_admin" ON profiles;
CREATE POLICY "profiles_delete_admin" ON profiles FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- nurse_profiles: admin can delete test nurse profiles
DROP POLICY IF EXISTS "nurse_profiles_delete_admin" ON nurse_profiles;
CREATE POLICY "nurse_profiles_delete_admin" ON nurse_profiles FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- hospitals: admin can delete test hospital profiles
DROP POLICY IF EXISTS "hospitals_delete_admin" ON hospitals;
CREATE POLICY "hospitals_delete_admin" ON hospitals FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- nurse_documents: admin can delete test documents
DROP POLICY IF EXISTS "nurse_documents_delete_admin" ON nurse_documents;
CREATE POLICY "nurse_documents_delete_admin" ON nurse_documents FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- hospital_documents: admin can delete test hospital documents
DROP POLICY IF EXISTS "hospital_documents_delete_admin" ON hospital_documents;
CREATE POLICY "hospital_documents_delete_admin" ON hospital_documents FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- saved_jobs: admin can delete saved jobs
DROP POLICY IF EXISTS "saved_jobs_delete_admin" ON saved_jobs;
CREATE POLICY "saved_jobs_delete_admin" ON saved_jobs FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- notifications: admin can delete notifications
DROP POLICY IF EXISTS "notifications_delete_admin" ON notifications;
CREATE POLICY "notifications_delete_admin" ON notifications FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );


-- ============ 2. STORED PROCEDURE: clean_test_data ============

CREATE OR REPLACE FUNCTION public.clean_test_data()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_deleted_reviews int;
  v_deleted_interviews int;
  v_deleted_applications int;
  v_deleted_saved_jobs int;
  v_deleted_job_matches int;
  v_deleted_jobs int;
  v_deleted_shifts int;
  v_deleted_nurse_docs int;
  v_deleted_hosp_docs int;
  v_deleted_nurse_profiles int;
  v_deleted_hospitals int;
  v_deleted_notifications int;
  v_deleted_profiles int;
BEGIN
  -- Verify caller is an authenticated platform administrator
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Unauthorized: Only platform administrators can clean test data.'
      USING ERRCODE = '42501';
  END IF;

  -- 1. Reviews
  DELETE FROM public.reviews;
  GET DIAGNOSTICS v_deleted_reviews = ROW_COUNT;

  -- 2. Interviews
  DELETE FROM public.interviews;
  GET DIAGNOSTICS v_deleted_interviews = ROW_COUNT;

  -- 3. Applications
  DELETE FROM public.applications;
  GET DIAGNOSTICS v_deleted_applications = ROW_COUNT;

  -- 4. Saved Jobs
  DELETE FROM public.saved_jobs;
  GET DIAGNOSTICS v_deleted_saved_jobs = ROW_COUNT;

  -- 5. Job Matches
  DELETE FROM public.job_matches;
  GET DIAGNOSTICS v_deleted_job_matches = ROW_COUNT;

  -- 6. Jobs
  DELETE FROM public.jobs;
  GET DIAGNOSTICS v_deleted_jobs = ROW_COUNT;

  -- 7. Shifts
  DELETE FROM public.shifts;
  GET DIAGNOSTICS v_deleted_shifts = ROW_COUNT;

  -- 8. Nurse Documents
  DELETE FROM public.nurse_documents;
  GET DIAGNOSTICS v_deleted_nurse_docs = ROW_COUNT;

  -- 9. Hospital Documents
  DELETE FROM public.hospital_documents;
  GET DIAGNOSTICS v_deleted_hosp_docs = ROW_COUNT;

  -- 10. Nurse Profiles
  DELETE FROM public.nurse_profiles;
  GET DIAGNOSTICS v_deleted_nurse_profiles = ROW_COUNT;

  -- 11. Hospitals
  DELETE FROM public.hospitals;
  GET DIAGNOSTICS v_deleted_hospitals = ROW_COUNT;

  -- 12. Notifications
  DELETE FROM public.notifications;
  GET DIAGNOSTICS v_deleted_notifications = ROW_COUNT;

  -- 13. Profiles (strictly preserve role = 'admin')
  DELETE FROM public.profiles WHERE role != 'admin';
  GET DIAGNOSTICS v_deleted_profiles = ROW_COUNT;

  RETURN jsonb_build_object(
    'success', true,
    'deleted_profiles', v_deleted_profiles,
    'deleted_hospitals', v_deleted_hospitals,
    'deleted_nurse_profiles', v_deleted_nurse_profiles,
    'deleted_jobs', v_deleted_jobs,
    'deleted_applications', v_deleted_applications,
    'deleted_interviews', v_deleted_interviews,
    'deleted_reviews', v_deleted_reviews,
    'deleted_nurse_docs', v_deleted_nurse_docs,
    'deleted_hosp_docs', v_deleted_hosp_docs,
    'deleted_saved_jobs', v_deleted_saved_jobs,
    'deleted_shifts', v_deleted_shifts,
    'deleted_notifications', v_deleted_notifications
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.clean_test_data() TO authenticated;


-- ============ 3. IMMEDIATE CLEANUP OF ALL TEST DATA ============

DELETE FROM public.reviews;
DELETE FROM public.interviews;
DELETE FROM public.applications;
DELETE FROM public.saved_jobs;
DELETE FROM public.job_matches;
DELETE FROM public.jobs;
DELETE FROM public.shifts;
DELETE FROM public.nurse_documents;
DELETE FROM public.hospital_documents;
DELETE FROM public.nurse_profiles;
DELETE FROM public.hospitals;
DELETE FROM public.notifications;
DELETE FROM public.profiles WHERE role != 'admin';



