/*
# Create nurse-documents storage bucket with secure RLS policies

1. Storage Changes
- Create a PRIVATE bucket named `nurse-documents` (public = false).
- No existing buckets are deleted.

2. Storage RLS Policies (on storage.objects)
- Nurses can upload files only to a path prefixed with their own auth.uid().
- Nurses can read/download only their own files (path = auth.uid()/...).
- Nurses can delete only their own files.
- Admins (profiles.role = 'admin') can read any file in the bucket for verification purposes.
- Hospital users get access only via signed URLs generated by the server/admin — NOT via storage RLS.
- Uses signed URLs for downloads so private files are never made public.

3. Security Notes
- Bucket is private: files are NOT publicly readable.
- Path-based isolation: each nurse's files live under `<uid>/` prefix, enforced by RLS.
- Admin read access is scoped to the admin role check via profiles table.
*/

-- Create the private bucket (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'nurse-documents',
  'nurse-documents',
  false,
  10485760,  -- 10 MB limit
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain']
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Storage RLS policies on storage.objects for nurse-documents
-- ============================================================

-- Nurses can upload to their own folder
DROP POLICY IF EXISTS "nurse_docs_upload_own" ON storage.objects;
CREATE POLICY "nurse_docs_upload_own"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'nurse-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Nurses can read their own files
DROP POLICY IF EXISTS "nurse_docs_read_own" ON storage.objects;
CREATE POLICY "nurse_docs_read_own"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Nurses can delete their own files
DROP POLICY IF EXISTS "nurse_docs_delete_own" ON storage.objects;
CREATE POLICY "nurse_docs_delete_own"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Admins can read any file in nurse-documents for verification
DROP POLICY IF EXISTS "nurse_docs_admin_read" ON storage.objects;
CREATE POLICY "nurse_docs_admin_read"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Admins can delete any file in nurse-documents (e.g. during moderation)
DROP POLICY IF EXISTS "nurse_docs_admin_delete" ON storage.objects;
CREATE POLICY "nurse_docs_admin_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'nurse-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);
